version: '3.8'

services:
  fish-speech:
    build: .
    container_name: fish-speech
    shm_size: 30gb
    volumes:
      - ./:/exp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: tail -f /dev/null
